apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: gmp-public
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
      smtp_from: 'seu-email@gmail.com'
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_auth_username: 'seu-email@gmail.com'
      smtp_auth_password: 'sua-app-password-aqui'  # App Password do Gmail
      smtp_require_tls: true

    route:
      group_by: ['alertname', 'severity']
      group_wait: 10s
      group_interval: 5m
      repeat_interval: 3h
      receiver: 'email-alerts'

    receivers:
    - name: 'email-alerts'
      email_configs:
      - to: 'seu-email@gmail.com'
        headers:
          Subject: '[{{ .Status | toUpper }}] {{ .GroupLabels.alertname }}'
        html: |
          <h2>Alerta Prometheus</h2>
          <p><strong>Status:</strong> {{ .Status }}</p>

          {{ range .Alerts }}
          <hr>
          <h3>{{ .Labels.alertname }}</h3>
          <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
          <p><strong>Summary:</strong> {{ .Annotations.summary }}</p>
          <p><strong>Description:</strong> {{ .Annotations.description }}</p>

          <h4>Labels:</h4>
          <ul>
          {{ range .Labels.SortedPairs }}
            <li><strong>{{ .Name }}:</strong> {{ .Value }}</li>
          {{ end }}
          </ul>
          {{ end }}

          <hr>
          <small>GMP Alertmanager - {{ .ExternalURL }}</small>
---
apiVersion: monitoring.googleapis.com/v1
kind: OperatorConfig
metadata:
  namespace: gmp-public
  name: config
spec:
  features:
    targetStatus:
      enabled: true
  managedAlertmanager:
    enabled: true
    configSecret:
      name: alertmanager-config
      key: alertmanager.yaml
